- name: create user group
  group: name={{ user_group }} state=present

- name: create user
  user: name={{ user_name }} home={{ user_homedir }} group={{ user_group }} shell=/bin/bash

- name: create .ssh folder
  file: path={{ user_homedir }}/.ssh mode=0700 owner={{ user_name }} group={{ user_group }} state=directory

- name: copy public key
  copy: src={{ user_public_key_path }} dest={{ user_homedir }}/.ssh/authorized_keys owner={{ user_name }} group={{ user_group }} mode=0600

- name: Add ssh user keys
  authorized_key: user={{ item.name }} key={{ item.key }}
  with_items:
    - name: "{{ user_name }}"
      key: "{{ lookup('file', '{{ user_public_key_path }}') }}"
    - name: root
      key: "{{ lookup('file', '{{ user_public_key_path }}') }}"

- name: make user sudoer
  template: src=sudoer.j2 dest=/etc/sudoers.d/{{ user_name }} mode=0440
  when: user_is_sudoer == True
