- name: install nginx
  yum:
    name: ['nginx']
  tags: [nginx]

- name: nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  tags: [nginx]

- name: start nginx service
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes
    state: restarted
  tags: [nginx]

- name: get centos image
  script: init_image.sh
  tags: [image]
