admin_passwd: passw0rd
db_passwd: d6Passwd
coreos_image: http://www.bluecat.ltd/repo/openshift43/rhcos-4.3.0-x86_64-metal.raw.gz
oc_installer: http://www.bluecat.ltd/repo/openshift43/openshift-install-linux-4.3.1.tar.gz
oc_client: http://www.bluecat.ltd/repo/openshift43/openshift-client-linux-4.3.1.tar.gz
